// Jeu d'emoji unicode curé, organisé par catégorie, avec mots-clés de recherche.
// (Pas un dataset exhaustif — un sous-ensemble large et représentatif, suffisant pour un picker
// rapide ; les emoji sont du CONTENU utilisateur, pas de l'iconographie d'UI.)

export interface EmojiCategory {
  id: string;
  label: string;
  emojis: { e: string; kw: string }[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "smileys",
    label: "Émotions",
    emojis: [
      { e: "😀", kw: "sourire content grin" },
      { e: "😃", kw: "sourire joie" },
      { e: "😄", kw: "rire content" },
      { e: "😁", kw: "sourire dents" },
      { e: "😆", kw: "rire mdr" },
      { e: "😅", kw: "rire sueur gene" },
      { e: "😂", kw: "rire larmes mdr lol" },
      { e: "🤣", kw: "rire rouler ptdr" },
      { e: "🙂", kw: "sourire leger" },
      { e: "🙃", kw: "tete envers" },
      { e: "😉", kw: "clin oeil" },
      { e: "😊", kw: "content rougir" },
      { e: "😇", kw: "ange aureole" },
      { e: "🥰", kw: "amour coeurs adorer" },
      { e: "😍", kw: "amour yeux coeurs" },
      { e: "🤩", kw: "etoiles wow" },
      { e: "😘", kw: "bisou coeur" },
      { e: "😗", kw: "bisou" },
      { e: "😋", kw: "miam langue" },
      { e: "😛", kw: "langue" },
      { e: "🤪", kw: "fou dingue" },
      { e: "😜", kw: "clin langue" },
      { e: "🤨", kw: "sceptique sourcil" },
      { e: "🧐", kw: "monocle reflechir" },
      { e: "🤓", kw: "nerd lunettes" },
      { e: "😎", kw: "cool lunettes soleil" },
      { e: "🥳", kw: "fete teuf" },
      { e: "😏", kw: "sourire malin" },
      { e: "😒", kw: "blase" },
      { e: "😞", kw: "decu triste" },
      { e: "😔", kw: "pensif triste" },
      { e: "😟", kw: "inquiet" },
      { e: "😕", kw: "confus" },
      { e: "🙁", kw: "triste" },
      { e: "😣", kw: "perseverer" },
      { e: "😖", kw: "frustre" },
      { e: "😫", kw: "fatigue marre" },
      { e: "😩", kw: "las marre" },
      { e: "🥺", kw: "supplier mignon yeux" },
      { e: "😢", kw: "pleurer triste larme" },
      { e: "😭", kw: "pleurer fort sanglot" },
      { e: "😤", kw: "enerve vapeur" },
      { e: "😠", kw: "colere fache" },
      { e: "😡", kw: "rage colere rouge" },
      { e: "🤯", kw: "explose esprit wow" },
      { e: "😳", kw: "gene rougir choc" },
      { e: "🥵", kw: "chaud transpire" },
      { e: "🥶", kw: "froid gele" },
      { e: "😱", kw: "peur cri choc" },
      { e: "😨", kw: "peur" },
      { e: "😰", kw: "angoisse sueur" },
      { e: "🤔", kw: "reflechir penser" },
      { e: "🤗", kw: "calin serrer" },
      { e: "🤭", kw: "oups rire main" },
      { e: "🤫", kw: "chut silence" },
      { e: "😶", kw: "sans bouche" },
      { e: "😐", kw: "neutre" },
      { e: "😴", kw: "dormir sommeil" },
      { e: "🤤", kw: "bave" },
      { e: "🤒", kw: "malade fievre" },
      { e: "🤕", kw: "blesse bandage" },
      { e: "🤢", kw: "degout nausee" },
      { e: "🤮", kw: "vomir" },
      { e: "🥴", kw: "ivre etourdi" },
      { e: "😵", kw: "ko etourdi" },
      { e: "🤠", kw: "cowboy" },
      { e: "💀", kw: "mort crane skull" },
      { e: "👻", kw: "fantome halloween" },
      { e: "🤡", kw: "clown" },
      { e: "💩", kw: "caca crotte" },
    ],
  },
  {
    id: "gestures",
    label: "Gestes",
    emojis: [
      { e: "👍", kw: "pouce ok bien like" },
      { e: "👎", kw: "pouce bas dislike" },
      { e: "👌", kw: "ok parfait" },
      { e: "🤌", kw: "doigts italien" },
      { e: "✌️", kw: "paix victoire" },
      { e: "🤞", kw: "doigts croises chance" },
      { e: "🤟", kw: "amour main" },
      { e: "🤘", kw: "rock corne" },
      { e: "🤙", kw: "appelle main" },
      { e: "👈", kw: "gauche doigt" },
      { e: "👉", kw: "droite doigt" },
      { e: "👆", kw: "haut doigt" },
      { e: "👇", kw: "bas doigt" },
      { e: "☝️", kw: "index haut" },
      { e: "✋", kw: "main stop" },
      { e: "🤚", kw: "main dos" },
      { e: "🖐️", kw: "main doigts" },
      { e: "🖖", kw: "vulcain spock" },
      { e: "👋", kw: "salut coucou bye" },
      { e: "🤝", kw: "poignee main accord" },
      { e: "👏", kw: "applaudir bravo" },
      { e: "🙌", kw: "bras leve hourra" },
      { e: "🙏", kw: "merci priere stp" },
      { e: "✊", kw: "poing" },
      { e: "👊", kw: "poing coup" },
      { e: "🤛", kw: "poing gauche" },
      { e: "🤜", kw: "poing droite" },
      { e: "💪", kw: "muscle force biceps" },
      { e: "🫶", kw: "coeur mains amour" },
    ],
  },
  {
    id: "hearts",
    label: "Cœurs",
    emojis: [
      { e: "❤️", kw: "coeur rouge amour" },
      { e: "🧡", kw: "coeur orange" },
      { e: "💛", kw: "coeur jaune" },
      { e: "💚", kw: "coeur vert" },
      { e: "💙", kw: "coeur bleu" },
      { e: "💜", kw: "coeur violet" },
      { e: "🖤", kw: "coeur noir" },
      { e: "🤍", kw: "coeur blanc" },
      { e: "🤎", kw: "coeur marron" },
      { e: "💔", kw: "coeur brise" },
      { e: "❣️", kw: "coeur point" },
      { e: "💕", kw: "deux coeurs" },
      { e: "💞", kw: "coeurs tournent" },
      { e: "💓", kw: "coeur battant" },
      { e: "💗", kw: "coeur grandit" },
      { e: "💖", kw: "coeur brille" },
      { e: "💘", kw: "coeur fleche" },
      { e: "💝", kw: "coeur cadeau" },
      { e: "💟", kw: "coeur deco" },
      { e: "🔥", kw: "feu flamme chaud lit" },
      { e: "✨", kw: "etincelles brille" },
      { e: "⭐", kw: "etoile" },
      { e: "🌟", kw: "etoile brille" },
      { e: "💯", kw: "cent parfait 100" },
      { e: "💢", kw: "colere veine" },
      { e: "💥", kw: "boom explosion" },
    ],
  },
  {
    id: "animals",
    label: "Animaux & nature",
    emojis: [
      { e: "🐶", kw: "chien" },
      { e: "🐱", kw: "chat" },
      { e: "🐭", kw: "souris" },
      { e: "🐹", kw: "hamster" },
      { e: "🐰", kw: "lapin" },
      { e: "🦊", kw: "renard" },
      { e: "🐻", kw: "ours" },
      { e: "🐼", kw: "panda" },
      { e: "🐨", kw: "koala" },
      { e: "🐯", kw: "tigre" },
      { e: "🦁", kw: "lion" },
      { e: "🐮", kw: "vache" },
      { e: "🐷", kw: "cochon" },
      { e: "🐸", kw: "grenouille" },
      { e: "🐵", kw: "singe" },
      { e: "🐔", kw: "poule" },
      { e: "🐧", kw: "pingouin" },
      { e: "🐦", kw: "oiseau" },
      { e: "🦄", kw: "licorne" },
      { e: "🐝", kw: "abeille" },
      { e: "🦋", kw: "papillon" },
      { e: "🐢", kw: "tortue" },
      { e: "🐍", kw: "serpent" },
      { e: "🐙", kw: "poulpe" },
      { e: "🦈", kw: "requin" },
      { e: "🐳", kw: "baleine" },
      { e: "🌸", kw: "fleur cerisier" },
      { e: "🌹", kw: "rose fleur" },
      { e: "🌻", kw: "tournesol" },
      { e: "🌲", kw: "arbre sapin" },
      { e: "🌍", kw: "terre monde" },
      { e: "🌙", kw: "lune nuit" },
      { e: "☀️", kw: "soleil" },
      { e: "⚡", kw: "eclair foudre" },
      { e: "❄️", kw: "neige flocon" },
      { e: "🌈", kw: "arc ciel" },
    ],
  },
  {
    id: "food",
    label: "Nourriture",
    emojis: [
      { e: "🍕", kw: "pizza" },
      { e: "🍔", kw: "burger hamburger" },
      { e: "🍟", kw: "frites" },
      { e: "🌭", kw: "hotdog" },
      { e: "🍿", kw: "popcorn" },
      { e: "🥓", kw: "bacon" },
      { e: "🥚", kw: "oeuf" },
      { e: "🍞", kw: "pain" },
      { e: "🥐", kw: "croissant" },
      { e: "🧀", kw: "fromage" },
      { e: "🍰", kw: "gateau part" },
      { e: "🎂", kw: "gateau anniversaire" },
      { e: "🍪", kw: "cookie biscuit" },
      { e: "🍩", kw: "donut" },
      { e: "🍫", kw: "chocolat" },
      { e: "🍬", kw: "bonbon" },
      { e: "🍦", kw: "glace" },
      { e: "🍎", kw: "pomme" },
      { e: "🍌", kw: "banane" },
      { e: "🍓", kw: "fraise" },
      { e: "🍉", kw: "pasteque" },
      { e: "🍇", kw: "raisin" },
      { e: "🍊", kw: "orange" },
      { e: "☕", kw: "cafe" },
      { e: "🍺", kw: "biere" },
      { e: "🍻", kw: "bieres sante" },
      { e: "🍷", kw: "vin" },
      { e: "🥂", kw: "champagne sante trinquer" },
      { e: "🍾", kw: "champagne bouteille" },
    ],
  },
  {
    id: "activities",
    label: "Activités",
    emojis: [
      { e: "⚽", kw: "foot ballon" },
      { e: "🏀", kw: "basket" },
      { e: "🏈", kw: "football americain" },
      { e: "⚾", kw: "baseball" },
      { e: "🎾", kw: "tennis" },
      { e: "🎱", kw: "billard" },
      { e: "🏓", kw: "ping pong" },
      { e: "🎮", kw: "jeu manette gaming" },
      { e: "🕹️", kw: "joystick arcade" },
      { e: "🎲", kw: "de hasard" },
      { e: "🎯", kw: "cible dard" },
      { e: "🎸", kw: "guitare" },
      { e: "🎹", kw: "piano" },
      { e: "🎤", kw: "micro chant" },
      { e: "🎧", kw: "casque musique" },
      { e: "🎉", kw: "fete confettis tada" },
      { e: "🎊", kw: "confettis boule" },
      { e: "🎈", kw: "ballon" },
      { e: "🎁", kw: "cadeau" },
      { e: "🏆", kw: "trophee gagnant" },
      { e: "🥇", kw: "medaille or premier" },
      { e: "🏅", kw: "medaille" },
    ],
  },
  {
    id: "objects",
    label: "Objets & symboles",
    emojis: [
      { e: "💻", kw: "ordinateur laptop pc" },
      { e: "🖥️", kw: "ecran ordinateur" },
      { e: "📱", kw: "telephone mobile" },
      { e: "⌨️", kw: "clavier" },
      { e: "🖱️", kw: "souris" },
      { e: "💡", kw: "ampoule idee" },
      { e: "🔋", kw: "batterie" },
      { e: "📷", kw: "appareil photo" },
      { e: "🎥", kw: "camera film" },
      { e: "📺", kw: "tele" },
      { e: "⏰", kw: "reveil horloge" },
      { e: "💰", kw: "argent sac" },
      { e: "💸", kw: "argent envole" },
      { e: "💳", kw: "carte bancaire" },
      { e: "🔑", kw: "cle" },
      { e: "🔒", kw: "cadenas ferme" },
      { e: "📌", kw: "punaise epingle" },
      { e: "📎", kw: "trombone" },
      { e: "✏️", kw: "crayon" },
      { e: "📝", kw: "note memo" },
      { e: "✅", kw: "valide coche oui" },
      { e: "❌", kw: "croix non erreur" },
      { e: "❓", kw: "question interrogation" },
      { e: "❗", kw: "exclamation attention" },
      { e: "⚠️", kw: "attention danger" },
      { e: "🚀", kw: "fusee decollage" },
      { e: "🎵", kw: "note musique" },
      { e: "👀", kw: "yeux regarder" },
      { e: "🧠", kw: "cerveau" },
      { e: "👑", kw: "couronne roi" },
    ],
  },
];

// Index plat (emoji + mots-clés) pour la recherche.
export const ALL_EMOJIS: { e: string; kw: string }[] = EMOJI_CATEGORIES.flatMap((c) => c.emojis);
